name: simulator_push_notification
version: 1.0.0+1
publish_to: none
description: This project is to implement the development of push notification facilities at the device simulator level
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  get_cli: any
  dcli: ^0.50.2
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

